name: example
description: Example Flutter project for temaki icon package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  temaki_flutter:
    path: ../

  reflectable: ^4.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  built_value_generator: ^8.4.2

flutter:
  uses-material-design: true
