targets:
  $default:
    builders:
      temaki_flutter|icon_class_builder:
        enabled: true
        generate_for:
          - lib/*.json

builders:
  icon_class_builder:
    import: "builder/icon_class_generator.dart"
    builder_factories: [ "iconSetBuilder" ]
    build_extensions: { ".json": [".dart"] }
    build_to: source
    auto_apply: root_package